# Site settings
title: Events @ Red Panthers
email: info@redpanthers.co
description: Um lindo tema feito para jekyll e com o <3
baseurl: "/"
url: "http://redpanthers.io/events"

author:
  name     : 'Harisankar P S'
  email    : hsps@redpanthers.co
  url      : http://redpanthers.co
  facebook : http://facebook.com/redpanthers.co
  twitter  : http://twitter.com/redpanthershq

github: https://github.com/redpanthers

paginate: 10
comments: false
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
