# Site settings
title: Red Panthers, Events
email: info@redpanthers.co
description: List of events organized, supported or sponsored by Red Panthers Kochi, India
baseurl: ""
url: "http://redpanthers.io/events"

author:
  name     : 'Harisankar P S'
  email    : hsps@redpanthers.co
  url      : http://redpanthers.co
  facebook : http://facebook.com/redpanthers.co
  twitter  : http://twitter.com/redpanthershq

github: https://github.com/redpanthers

paginate: 10
comments: false
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
